// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entropy/configuration/parser/vm.proto

package entropy.configuration.parser;

public final class PBVirtualMachine {
    private PBVirtualMachine() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface VirtualMachineOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string name = 1;
        boolean hasName();

        String getName();

        // optional int32 nbOfCPUs = 2;
        boolean hasNbOfCPUs();

        int getNbOfCPUs();

        // optional int32 memoryConsumption = 3;
        boolean hasMemoryConsumption();

        int getMemoryConsumption();

        // optional int32 cpuConsumption = 4;
        boolean hasCpuConsumption();

        int getCpuConsumption();

        // optional int32 memoryDemand = 5;
        boolean hasMemoryDemand();

        int getMemoryDemand();

        // optional int32 cpuDemand = 6;
        boolean hasCpuDemand();

        int getCpuDemand();

        // optional int32 cpuMax = 7;
        boolean hasCpuMax();

        int getCpuMax();

        // optional string template = 8;
        boolean hasTemplate();

        String getTemplate();

        // optional string hostingPlatform = 9;
        boolean hasHostingPlatform();

        String getHostingPlatform();

        // repeated .VirtualMachine.Option options = 10;
        java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option>
        getOptionsList();

        entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option getOptions(int index);

        int getOptionsCount();

        java.util.List<? extends entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder>
        getOptionsOrBuilderList();

        entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder getOptionsOrBuilder(
                int index);
    }

    public static final class VirtualMachine extends
            com.google.protobuf.GeneratedMessage
            implements VirtualMachineOrBuilder {
        // Use VirtualMachine.newBuilder() to construct.
        private VirtualMachine(Builder builder) {
            super(builder);
        }

        private VirtualMachine(boolean noInit) {
        }

        private static final VirtualMachine defaultInstance;

        public static VirtualMachine getDefaultInstance() {
            return defaultInstance;
        }

        public VirtualMachine getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_fieldAccessorTable;
        }

        public interface OptionOrBuilder
                extends com.google.protobuf.MessageOrBuilder {

            // required string key = 1;
            boolean hasKey();

            String getKey();

            // optional string value = 2;
            boolean hasValue();

            String getValue();
        }

        public static final class Option extends
                com.google.protobuf.GeneratedMessage
                implements OptionOrBuilder {
            // Use Option.newBuilder() to construct.
            private Option(Builder builder) {
                super(builder);
            }

            private Option(boolean noInit) {
            }

            private static final Option defaultInstance;

            public static Option getDefaultInstance() {
                return defaultInstance;
            }

            public Option getDefaultInstanceForType() {
                return defaultInstance;
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_Option_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_Option_fieldAccessorTable;
            }

            private int bitField0_;
            // required string key = 1;
            public static final int KEY_FIELD_NUMBER = 1;
            private java.lang.Object key_;

            public boolean hasKey() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getKey() {
                java.lang.Object ref = key_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                        key_ = s;
                    }
                    return s;
                }
            }

            private com.google.protobuf.ByteString getKeyBytes() {
                java.lang.Object ref = key_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    key_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            // optional string value = 2;
            public static final int VALUE_FIELD_NUMBER = 2;
            private java.lang.Object value_;

            public boolean hasValue() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getValue() {
                java.lang.Object ref = value_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                        value_ = s;
                    }
                    return s;
                }
            }

            private com.google.protobuf.ByteString getValueBytes() {
                java.lang.Object ref = value_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    value_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            private void initFields() {
                key_ = "";
                value_ = "";
            }

            private byte memoizedIsInitialized = -1;

            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized != -1) return isInitialized == 1;

                if (!hasKey()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeBytes(1, getKeyBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeBytes(2, getValueBytes());
                }
                getUnknownFields().writeTo(output);
            }

            private int memoizedSerializedSize = -1;

            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1) return size;

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(1, getKeyBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(2, getValueBytes());
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;

            @java.lang.Override
            protected java.lang.Object writeReplace()
                    throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data).buildParsed();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data, extensionRegistry)
                        .buildParsed();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data).buildParsed();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data, extensionRegistry)
                        .buildParsed();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input).buildParsed();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input, extensionRegistry)
                        .buildParsed();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                Builder builder = newBuilder();
                if (builder.mergeDelimitedFrom(input)) {
                    return builder.buildParsed();
                } else {
                    return null;
                }
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Builder builder = newBuilder();
                if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                    return builder.buildParsed();
                } else {
                    return null;
                }
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input).buildParsed();
            }

            public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input, extensionRegistry)
                        .buildParsed();
            }

            public static Builder newBuilder() {
                return Builder.create();
            }

            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder(entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option prototype) {
                return newBuilder().mergeFrom(prototype);
            }

            public Builder toBuilder() {
                return newBuilder(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            public static final class Builder extends
                    com.google.protobuf.GeneratedMessage.Builder<Builder>
                    implements entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_Option_descriptor;
                }

                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_Option_fieldAccessorTable;
                }

                // Construct using entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }

                private static Builder create() {
                    return new Builder();
                }

                public Builder clear() {
                    super.clear();
                    key_ = "";
                    bitField0_ = (bitField0_ & ~0x00000001);
                    value_ = "";
                    bitField0_ = (bitField0_ & ~0x00000002);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.getDescriptor();
                }

                public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option getDefaultInstanceForType() {
                    return entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.getDefaultInstance();
                }

                public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option build() {
                    entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                private entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option buildParsed()
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(
                                result).asInvalidProtocolBufferException();
                    }
                    return result;
                }

                public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option buildPartial() {
                    entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option result = new entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option(this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.key_ = key_;
                    if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.value_ = value_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option) {
                        return mergeFrom((entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option other) {
                    if (other == entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.getDefaultInstance())
                        return this;
                    if (other.hasKey()) {
                        setKey(other.getKey());
                    }
                    if (other.hasValue()) {
                        setValue(other.getValue());
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    if (!hasKey()) {

                        return false;
                    }
                    return true;
                }

                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                            com.google.protobuf.UnknownFieldSet.newBuilder(
                                    this.getUnknownFields());
                    while (true) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            default: {
                                if (!parseUnknownField(input, unknownFields,
                                        extensionRegistry, tag)) {
                                    this.setUnknownFields(unknownFields.build());
                                    onChanged();
                                    return this;
                                }
                                break;
                            }
                            case 10: {
                                bitField0_ |= 0x00000001;
                                key_ = input.readBytes();
                                break;
                            }
                            case 18: {
                                bitField0_ |= 0x00000002;
                                value_ = input.readBytes();
                                break;
                            }
                        }
                    }
                }

                private int bitField0_;

                // required string key = 1;
                private java.lang.Object key_ = "";

                public boolean hasKey() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }

                public String getKey() {
                    java.lang.Object ref = key_;
                    if (!(ref instanceof String)) {
                        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                        key_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                public Builder setKey(String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    key_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearKey() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    key_ = getDefaultInstance().getKey();
                    onChanged();
                    return this;
                }

                void setKey(com.google.protobuf.ByteString value) {
                    bitField0_ |= 0x00000001;
                    key_ = value;
                    onChanged();
                }

                // optional string value = 2;
                private java.lang.Object value_ = "";

                public boolean hasValue() {
                    return ((bitField0_ & 0x00000002) == 0x00000002);
                }

                public String getValue() {
                    java.lang.Object ref = value_;
                    if (!(ref instanceof String)) {
                        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                        value_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                public Builder setValue(String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    value_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearValue() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    value_ = getDefaultInstance().getValue();
                    onChanged();
                    return this;
                }

                void setValue(com.google.protobuf.ByteString value) {
                    bitField0_ |= 0x00000002;
                    value_ = value;
                    onChanged();
                }

                // @@protoc_insertion_point(builder_scope:VirtualMachine.Option)
            }

            static {
                defaultInstance = new Option(true);
                defaultInstance.initFields();
            }

            // @@protoc_insertion_point(class_scope:VirtualMachine.Option)
        }

        private int bitField0_;
        // required string name = 1;
        public static final int NAME_FIELD_NUMBER = 1;
        private java.lang.Object name_;

        public boolean hasName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    name_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional int32 nbOfCPUs = 2;
        public static final int NBOFCPUS_FIELD_NUMBER = 2;
        private int nbOfCPUs_;

        public boolean hasNbOfCPUs() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getNbOfCPUs() {
            return nbOfCPUs_;
        }

        // optional int32 memoryConsumption = 3;
        public static final int MEMORYCONSUMPTION_FIELD_NUMBER = 3;
        private int memoryConsumption_;

        public boolean hasMemoryConsumption() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public int getMemoryConsumption() {
            return memoryConsumption_;
        }

        // optional int32 cpuConsumption = 4;
        public static final int CPUCONSUMPTION_FIELD_NUMBER = 4;
        private int cpuConsumption_;

        public boolean hasCpuConsumption() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getCpuConsumption() {
            return cpuConsumption_;
        }

        // optional int32 memoryDemand = 5;
        public static final int MEMORYDEMAND_FIELD_NUMBER = 5;
        private int memoryDemand_;

        public boolean hasMemoryDemand() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public int getMemoryDemand() {
            return memoryDemand_;
        }

        // optional int32 cpuDemand = 6;
        public static final int CPUDEMAND_FIELD_NUMBER = 6;
        private int cpuDemand_;

        public boolean hasCpuDemand() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public int getCpuDemand() {
            return cpuDemand_;
        }

        // optional int32 cpuMax = 7;
        public static final int CPUMAX_FIELD_NUMBER = 7;
        private int cpuMax_;

        public boolean hasCpuMax() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        public int getCpuMax() {
            return cpuMax_;
        }

        // optional string template = 8;
        public static final int TEMPLATE_FIELD_NUMBER = 8;
        private java.lang.Object template_;

        public boolean hasTemplate() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }

        public String getTemplate() {
            java.lang.Object ref = template_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    template_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getTemplateBytes() {
            java.lang.Object ref = template_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                template_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string hostingPlatform = 9;
        public static final int HOSTINGPLATFORM_FIELD_NUMBER = 9;
        private java.lang.Object hostingPlatform_;

        public boolean hasHostingPlatform() {
            return ((bitField0_ & 0x00000100) == 0x00000100);
        }

        public String getHostingPlatform() {
            java.lang.Object ref = hostingPlatform_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    hostingPlatform_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getHostingPlatformBytes() {
            java.lang.Object ref = hostingPlatform_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                hostingPlatform_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // repeated .VirtualMachine.Option options = 10;
        public static final int OPTIONS_FIELD_NUMBER = 10;
        private java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option> options_;

        public java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option> getOptionsList() {
            return options_;
        }

        public java.util.List<? extends entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder>
        getOptionsOrBuilderList() {
            return options_;
        }

        public int getOptionsCount() {
            return options_.size();
        }

        public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option getOptions(int index) {
            return options_.get(index);
        }

        public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder getOptionsOrBuilder(
                int index) {
            return options_.get(index);
        }

        private void initFields() {
            name_ = "";
            nbOfCPUs_ = 0;
            memoryConsumption_ = 0;
            cpuConsumption_ = 0;
            memoryDemand_ = 0;
            cpuDemand_ = 0;
            cpuMax_ = 0;
            template_ = "";
            hostingPlatform_ = "";
            options_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            for (int i = 0; i < getOptionsCount(); i++) {
                if (!getOptions(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, nbOfCPUs_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, memoryConsumption_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, cpuConsumption_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt32(5, memoryDemand_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeInt32(6, cpuDemand_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeInt32(7, cpuMax_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeBytes(8, getTemplateBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                output.writeBytes(9, getHostingPlatformBytes());
            }
            for (int i = 0; i < options_.size(); i++) {
                output.writeMessage(10, options_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, nbOfCPUs_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, memoryConsumption_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, cpuConsumption_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, memoryDemand_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, cpuDemand_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(7, cpuMax_);
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(8, getTemplateBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(9, getHostingPlatformBytes());
            }
            for (int i = 0; i < options_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(10, options_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(entropy.configuration.parser.PBVirtualMachine.VirtualMachine prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements entropy.configuration.parser.PBVirtualMachine.VirtualMachineOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_fieldAccessorTable;
            }

            // Construct using entropy.configuration.parser.PBVirtualMachine.VirtualMachine.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getOptionsFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                nbOfCPUs_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                memoryConsumption_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                cpuConsumption_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                memoryDemand_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                cpuDemand_ = 0;
                bitField0_ = (bitField0_ & ~0x00000020);
                cpuMax_ = 0;
                bitField0_ = (bitField0_ & ~0x00000040);
                template_ = "";
                bitField0_ = (bitField0_ & ~0x00000080);
                hostingPlatform_ = "";
                bitField0_ = (bitField0_ & ~0x00000100);
                if (optionsBuilder_ == null) {
                    options_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000200);
                } else {
                    optionsBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDescriptor();
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine getDefaultInstanceForType() {
                return entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDefaultInstance();
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine build() {
                entropy.configuration.parser.PBVirtualMachine.VirtualMachine result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private entropy.configuration.parser.PBVirtualMachine.VirtualMachine buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                entropy.configuration.parser.PBVirtualMachine.VirtualMachine result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine buildPartial() {
                entropy.configuration.parser.PBVirtualMachine.VirtualMachine result = new entropy.configuration.parser.PBVirtualMachine.VirtualMachine(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.nbOfCPUs_ = nbOfCPUs_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.memoryConsumption_ = memoryConsumption_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.cpuConsumption_ = cpuConsumption_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.memoryDemand_ = memoryDemand_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.cpuDemand_ = cpuDemand_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.cpuMax_ = cpuMax_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.template_ = template_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000100;
                }
                result.hostingPlatform_ = hostingPlatform_;
                if (optionsBuilder_ == null) {
                    if (((bitField0_ & 0x00000200) == 0x00000200)) {
                        options_ = java.util.Collections.unmodifiableList(options_);
                        bitField0_ = (bitField0_ & ~0x00000200);
                    }
                    result.options_ = options_;
                } else {
                    result.options_ = optionsBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof entropy.configuration.parser.PBVirtualMachine.VirtualMachine) {
                    return mergeFrom((entropy.configuration.parser.PBVirtualMachine.VirtualMachine) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(entropy.configuration.parser.PBVirtualMachine.VirtualMachine other) {
                if (other == entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDefaultInstance())
                    return this;
                if (other.hasName()) {
                    setName(other.getName());
                }
                if (other.hasNbOfCPUs()) {
                    setNbOfCPUs(other.getNbOfCPUs());
                }
                if (other.hasMemoryConsumption()) {
                    setMemoryConsumption(other.getMemoryConsumption());
                }
                if (other.hasCpuConsumption()) {
                    setCpuConsumption(other.getCpuConsumption());
                }
                if (other.hasMemoryDemand()) {
                    setMemoryDemand(other.getMemoryDemand());
                }
                if (other.hasCpuDemand()) {
                    setCpuDemand(other.getCpuDemand());
                }
                if (other.hasCpuMax()) {
                    setCpuMax(other.getCpuMax());
                }
                if (other.hasTemplate()) {
                    setTemplate(other.getTemplate());
                }
                if (other.hasHostingPlatform()) {
                    setHostingPlatform(other.getHostingPlatform());
                }
                if (optionsBuilder_ == null) {
                    if (!other.options_.isEmpty()) {
                        if (options_.isEmpty()) {
                            options_ = other.options_;
                            bitField0_ = (bitField0_ & ~0x00000200);
                        } else {
                            ensureOptionsIsMutable();
                            options_.addAll(other.options_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.options_.isEmpty()) {
                        if (optionsBuilder_.isEmpty()) {
                            optionsBuilder_.dispose();
                            optionsBuilder_ = null;
                            options_ = other.options_;
                            bitField0_ = (bitField0_ & ~0x00000200);
                            optionsBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getOptionsFieldBuilder() : null;
                        } else {
                            optionsBuilder_.addAllMessages(other.options_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasName()) {

                    return false;
                }
                for (int i = 0; i < getOptionsCount(); i++) {
                    if (!getOptions(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            name_ = input.readBytes();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            nbOfCPUs_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            memoryConsumption_ = input.readInt32();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            cpuConsumption_ = input.readInt32();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            memoryDemand_ = input.readInt32();
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000020;
                            cpuDemand_ = input.readInt32();
                            break;
                        }
                        case 56: {
                            bitField0_ |= 0x00000040;
                            cpuMax_ = input.readInt32();
                            break;
                        }
                        case 66: {
                            bitField0_ |= 0x00000080;
                            template_ = input.readBytes();
                            break;
                        }
                        case 74: {
                            bitField0_ |= 0x00000100;
                            hostingPlatform_ = input.readBytes();
                            break;
                        }
                        case 82: {
                            entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder subBuilder = entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addOptions(subBuilder.buildPartial());
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string name = 1;
            private java.lang.Object name_ = "";

            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }

            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            void setName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
            }

            // optional int32 nbOfCPUs = 2;
            private int nbOfCPUs_;

            public boolean hasNbOfCPUs() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getNbOfCPUs() {
                return nbOfCPUs_;
            }

            public Builder setNbOfCPUs(int value) {
                bitField0_ |= 0x00000002;
                nbOfCPUs_ = value;
                onChanged();
                return this;
            }

            public Builder clearNbOfCPUs() {
                bitField0_ = (bitField0_ & ~0x00000002);
                nbOfCPUs_ = 0;
                onChanged();
                return this;
            }

            // optional int32 memoryConsumption = 3;
            private int memoryConsumption_;

            public boolean hasMemoryConsumption() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public int getMemoryConsumption() {
                return memoryConsumption_;
            }

            public Builder setMemoryConsumption(int value) {
                bitField0_ |= 0x00000004;
                memoryConsumption_ = value;
                onChanged();
                return this;
            }

            public Builder clearMemoryConsumption() {
                bitField0_ = (bitField0_ & ~0x00000004);
                memoryConsumption_ = 0;
                onChanged();
                return this;
            }

            // optional int32 cpuConsumption = 4;
            private int cpuConsumption_;

            public boolean hasCpuConsumption() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getCpuConsumption() {
                return cpuConsumption_;
            }

            public Builder setCpuConsumption(int value) {
                bitField0_ |= 0x00000008;
                cpuConsumption_ = value;
                onChanged();
                return this;
            }

            public Builder clearCpuConsumption() {
                bitField0_ = (bitField0_ & ~0x00000008);
                cpuConsumption_ = 0;
                onChanged();
                return this;
            }

            // optional int32 memoryDemand = 5;
            private int memoryDemand_;

            public boolean hasMemoryDemand() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public int getMemoryDemand() {
                return memoryDemand_;
            }

            public Builder setMemoryDemand(int value) {
                bitField0_ |= 0x00000010;
                memoryDemand_ = value;
                onChanged();
                return this;
            }

            public Builder clearMemoryDemand() {
                bitField0_ = (bitField0_ & ~0x00000010);
                memoryDemand_ = 0;
                onChanged();
                return this;
            }

            // optional int32 cpuDemand = 6;
            private int cpuDemand_;

            public boolean hasCpuDemand() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public int getCpuDemand() {
                return cpuDemand_;
            }

            public Builder setCpuDemand(int value) {
                bitField0_ |= 0x00000020;
                cpuDemand_ = value;
                onChanged();
                return this;
            }

            public Builder clearCpuDemand() {
                bitField0_ = (bitField0_ & ~0x00000020);
                cpuDemand_ = 0;
                onChanged();
                return this;
            }

            // optional int32 cpuMax = 7;
            private int cpuMax_;

            public boolean hasCpuMax() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            public int getCpuMax() {
                return cpuMax_;
            }

            public Builder setCpuMax(int value) {
                bitField0_ |= 0x00000040;
                cpuMax_ = value;
                onChanged();
                return this;
            }

            public Builder clearCpuMax() {
                bitField0_ = (bitField0_ & ~0x00000040);
                cpuMax_ = 0;
                onChanged();
                return this;
            }

            // optional string template = 8;
            private java.lang.Object template_ = "";

            public boolean hasTemplate() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }

            public String getTemplate() {
                java.lang.Object ref = template_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    template_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setTemplate(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                template_ = value;
                onChanged();
                return this;
            }

            public Builder clearTemplate() {
                bitField0_ = (bitField0_ & ~0x00000080);
                template_ = getDefaultInstance().getTemplate();
                onChanged();
                return this;
            }

            void setTemplate(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000080;
                template_ = value;
                onChanged();
            }

            // optional string hostingPlatform = 9;
            private java.lang.Object hostingPlatform_ = "";

            public boolean hasHostingPlatform() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }

            public String getHostingPlatform() {
                java.lang.Object ref = hostingPlatform_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    hostingPlatform_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setHostingPlatform(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                hostingPlatform_ = value;
                onChanged();
                return this;
            }

            public Builder clearHostingPlatform() {
                bitField0_ = (bitField0_ & ~0x00000100);
                hostingPlatform_ = getDefaultInstance().getHostingPlatform();
                onChanged();
                return this;
            }

            void setHostingPlatform(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000100;
                hostingPlatform_ = value;
                onChanged();
            }

            // repeated .VirtualMachine.Option options = 10;
            private java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option> options_ =
                    java.util.Collections.emptyList();

            private void ensureOptionsIsMutable() {
                if (!((bitField0_ & 0x00000200) == 0x00000200)) {
                    options_ = new java.util.ArrayList<entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option>(options_);
                    bitField0_ |= 0x00000200;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder> optionsBuilder_;

            public java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option> getOptionsList() {
                if (optionsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(options_);
                } else {
                    return optionsBuilder_.getMessageList();
                }
            }

            public int getOptionsCount() {
                if (optionsBuilder_ == null) {
                    return options_.size();
                } else {
                    return optionsBuilder_.getCount();
                }
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option getOptions(int index) {
                if (optionsBuilder_ == null) {
                    return options_.get(index);
                } else {
                    return optionsBuilder_.getMessage(index);
                }
            }

            public Builder setOptions(
                    int index, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option value) {
                if (optionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOptionsIsMutable();
                    options_.set(index, value);
                    onChanged();
                } else {
                    optionsBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setOptions(
                    int index, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder builderForValue) {
                if (optionsBuilder_ == null) {
                    ensureOptionsIsMutable();
                    options_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    optionsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addOptions(entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option value) {
                if (optionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOptionsIsMutable();
                    options_.add(value);
                    onChanged();
                } else {
                    optionsBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addOptions(
                    int index, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option value) {
                if (optionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureOptionsIsMutable();
                    options_.add(index, value);
                    onChanged();
                } else {
                    optionsBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addOptions(
                    entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder builderForValue) {
                if (optionsBuilder_ == null) {
                    ensureOptionsIsMutable();
                    options_.add(builderForValue.build());
                    onChanged();
                } else {
                    optionsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addOptions(
                    int index, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder builderForValue) {
                if (optionsBuilder_ == null) {
                    ensureOptionsIsMutable();
                    options_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    optionsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllOptions(
                    java.lang.Iterable<? extends entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option> values) {
                if (optionsBuilder_ == null) {
                    ensureOptionsIsMutable();
                    super.addAll(values, options_);
                    onChanged();
                } else {
                    optionsBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearOptions() {
                if (optionsBuilder_ == null) {
                    options_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000200);
                    onChanged();
                } else {
                    optionsBuilder_.clear();
                }
                return this;
            }

            public Builder removeOptions(int index) {
                if (optionsBuilder_ == null) {
                    ensureOptionsIsMutable();
                    options_.remove(index);
                    onChanged();
                } else {
                    optionsBuilder_.remove(index);
                }
                return this;
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder getOptionsBuilder(
                    int index) {
                return getOptionsFieldBuilder().getBuilder(index);
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder getOptionsOrBuilder(
                    int index) {
                if (optionsBuilder_ == null) {
                    return options_.get(index);
                } else {
                    return optionsBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder>
            getOptionsOrBuilderList() {
                if (optionsBuilder_ != null) {
                    return optionsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(options_);
                }
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder addOptionsBuilder() {
                return getOptionsFieldBuilder().addBuilder(
                        entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.getDefaultInstance());
            }

            public entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder addOptionsBuilder(
                    int index) {
                return getOptionsFieldBuilder().addBuilder(
                        index, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.getDefaultInstance());
            }

            public java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder>
            getOptionsBuilderList() {
                return getOptionsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder>
            getOptionsFieldBuilder() {
                if (optionsBuilder_ == null) {
                    optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.OptionOrBuilder>(
                            options_,
                            ((bitField0_ & 0x00000200) == 0x00000200),
                            getParentForChildren(),
                            isClean());
                    options_ = null;
                }
                return optionsBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:VirtualMachine)
        }

        static {
            defaultInstance = new VirtualMachine(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:VirtualMachine)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_VirtualMachine_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_VirtualMachine_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_VirtualMachine_Option_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_VirtualMachine_Option_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n%entropy/configuration/parser/vm.proto\"" +
                        "\226\002\n\016VirtualMachine\022\014\n\004name\030\001 \002(\t\022\020\n\010nbOf" +
                        "CPUs\030\002 \001(\005\022\031\n\021memoryConsumption\030\003 \001(\005\022\026\n" +
                        "\016cpuConsumption\030\004 \001(\005\022\024\n\014memoryDemand\030\005 " +
                        "\001(\005\022\021\n\tcpuDemand\030\006 \001(\005\022\016\n\006cpuMax\030\007 \001(\005\022\020" +
                        "\n\010template\030\010 \001(\t\022\027\n\017hostingPlatform\030\t \001(" +
                        "\t\022\'\n\007options\030\n \003(\0132\026.VirtualMachine.Opti" +
                        "on\032$\n\006Option\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \001(\t" +
                        "B0\n\034entropy.configuration.parserB\020PBVirt" +
                        "ualMachine"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_VirtualMachine_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_VirtualMachine_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_VirtualMachine_descriptor,
                                new java.lang.String[]{"Name", "NbOfCPUs", "MemoryConsumption", "CpuConsumption", "MemoryDemand", "CpuDemand", "CpuMax", "Template", "HostingPlatform", "Options",},
                                entropy.configuration.parser.PBVirtualMachine.VirtualMachine.class,
                                entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Builder.class);
                        internal_static_VirtualMachine_Option_descriptor =
                                internal_static_VirtualMachine_descriptor.getNestedTypes().get(0);
                        internal_static_VirtualMachine_Option_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_VirtualMachine_Option_descriptor,
                                new java.lang.String[]{"Key", "Value",},
                                entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.class,
                                entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Option.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
